CREATE TABLE books(
	book_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	publisher_id INTEGER UNSIGNED NOT NULL,
	titulo VARCHAR(60) NOT NULL,
	autor VARCHAR(100) NOT NULL,
	price DECIMAL(5,2)
);

CREATE TABLE publishers(
	publisher_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	country VARCHAR(20)
);

CREATE TABLE users(
	user_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE
);



CREATE TABLE books(
	book_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	field_1 TINYINT(2) NOT NULL,
	field_2 BOOLEAN,
	fecha DATE NOT NULL,
	hora TIME NOT NULL,
	tiempo DATETIME NOT NULL,
	field_3 DECIMAL(5,3)
);

CREATE TABLE publishers(
	publiher_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	field_2 VARCHAR(3) NOT NULL,
	email VARCHAR(5) NOT NULL UNIQUE
);

CREATE TABLE objetos(
	objeto_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	field_2 TEXT(300) NOT NULL,
	field_3 LONGTEXT(16777216) NOT NULL
);

CREATE TABLE chulas(
	chula_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	field_2 SMALLINT(3) NOT NULL,
	field_3 BIGINT(19) NOT NULL
);

