CREATE TABLE books(
	book_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	field_1 TINYINT(2) NOT NULL,
	field_2 BOOLEAN,
	fecha DATE NOT NULL,
	hora TIME NOT NULL,
	tiempo DATETIME NOT NULL,
	field_3 DECIMAL(5,3)
);